main: su.nightexpress.excellentenchants.EnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
description: 75+ 个类似原版风格的附魔，并实现无缝集成！
depend: [ nightcore ]
softdepend:
  - ProtocolLib
  - packetevents
  - PlaceholderAPI
  - MythicMobs
api-version: 1.21
load: STARTUP